sports_with_scores = ["americanfootball_cfl", "americanfootball_ncaaf", "americanfootball_nfl", "aussierules_afl",
                      "baseball_mlb", "baseball_ncaa", "basketball_nba", "basketball_wnba", "basketball_ncaab",
                      "icehockey_nhl", "rugbyleague_nrl", "soccer_argentina_primera_division",
                      "soccer_australia_aleague", "soccer_austria_bundesliga", "soccer_belgium_first_div",
                      "soccer_brazil_campeonato", "soccer_brazil_serie_b", "soccer_chile_campeonato",
                      "soccer_china_superleague", "soccer_denmark_superliga", "soccer_efl_champ",
                      "soccer_england_efl_cup", "soccer_england_league1", "soccer_england_league2", "soccer_epl",
                      "soccer_fa_cup", "soccer_fifa_world_cup", "soccer_fifa_world_cup_womens",
                      "soccer_finland_veikkausliiga", "soccer_france_ligue_one", "soccer_france_ligue_two",
                      "soccer_germany_bundesliga", "soccer_germany_bundesliga2", "soccer_germany_liga3",
                      "soccer_greece_super_league", "soccer_italy_serie_a", "soccer_italy_serie_b",
                      "soccer_japan_j_league", "soccer_korea_kleague1", "soccer_league_of_ireland",
                      "soccer_mexico_ligamx", "soccer_netherlands_eredivisie", "soccer_norway_eliteserien",
                      "soccer_poland_ekstraklasa", "soccer_portugal_primeira_liga", "soccer_spain_la_liga",
                      "soccer_spain_segunda_division", "soccer_spl", "soccer_sweden_allsvenskan",
                      "soccer_sweden_superettan", "soccer_switzerland_superleague", "soccer_turkey_super_league",
                      "soccer_uefa_champs_league", "soccer_uefa_champs_league_qualification",
                      "soccer_uefa_europa_league", "soccer_usa_mls"]
